### ISSUE TITLE
Empty list of documents leads to 500 error

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-editor-fe#6]
the request in

https://github.com/gawati/gawati-client-data/issues/1

is triggered by:

request:

POST /gwc/documents HTTP/1.0
Host: localhost:9102
Accept: application/json, text/plain, */*
Origin: https://data.dev.gawati.org
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJUanFuNUc3b3VKUi0wMWdlWVYtOEl6bzg1blplQzBQZC1KM2tOT1dmbC1ZIn0.eyJqdGkiOiJkZTdlYzljZi04YT
E1LTRiODUtYjIzNy1iYjlkZjFhOGZlZWYiLCJleHAiOjE1MjU4NTUxNzUsIm5iZiI6MCwiaWF0IjoxNTI1ODU0ODc1LCJpc3MiOiJodHRwczovL2F1dGguZ2F3YXRpLm9yZy9hdXRoL3JlYWxtcy9nYXdhdGkub3
JnIiwiYXVkIjoiZ2F3YXRpLWNsaWVudCIsInN1YiI6ImRjN2I5ODhkLTYyNDktNDZiZS04NzM5LWU4NmNmOWViNWFjNSIsInR5cCI6IkJlYXJlciIsImF6cCI6Imdhd2F0aS1jbGllbnQiLCJub25jZSI6IjllYz
dkZjczLWI0MTMtNDQ3ZC04MDcyLTViZWUzMTkwZDdlMSIsImF1dGhfdGltZSI6MTUyNTg1NDgzMiwic2Vzc2lvbl9zdGF0ZSI6ImU0Y2Q3YjBkLWU3MjgtNDk4Yy1iYjlhLThjMjlmMTVmNmNjZiIsImFjciI6Ij
AiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cHM6Ly9tZWRpYS5kZXYuZ2F3YXRpLm9yZyIsImh0dHBzOi8vZGF0YS5kZXYuZ2F3YXRpLm9yZyIsImh0dHBzOi8vZWRpdC5kZXYuZ2F3YXRpLm9yZyIsImh0dHBzOi
8vZGV2Lmdhd2F0aS5vcmciXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudC
IsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwibmFtZSI6IlRlc3QgR2F3YXRpIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzdCIsImdpdmVuX25hbWUiOiJUZXN0IiwiZmFtaWx5X2
5hbWUiOiJHYXdhdGkiLCJlbWFpbCI6InRlc3RAZ2F3YXRpLm9yZyJ9.HiaC10zKd_LbUQ126NH2RbRb5ahOr9WfuXvkccQKrLjuzXZGInfWXFmDtAIc2DkQP3OCjrGtB8i8lzg--0GGn7KigiehDPbxPL2qQOrfH
O47lNjv4Pa7gDlnT8Rs71NSIEwTnB2jV1r2dmz4ZFPTNdqxTLxNidlo3s6Ug1rnGA8PY1Bw7jUqNuwusOWsmuAJtM2zcidQ31_RlYD7pOl7nBW4HZBxPRfb71uekH0GOADZnr3xCpQzbuUhByzIphEwGxWx9wd0X
iCtJNMxr-qhwqBhkAFD-00RCzlNLwcuXP6raf94xZg_YMAiFqFG04HVWsE3X3KqttvmDCAlXnzONg
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Content-Type: application/json
Referer: https://data.dev.gawati.org/_lang/en/dashboard
Accept-Encoding: gzip, deflate, br
Accept-Language: en,en-US;q=0.9,de-DE;q=0.8,de;q=0.7
X-Forwarded-For: 109.164.203.165
X-Forwarded-Host: data.dev.gawati.org
X-Forwarded-Server: data.dev.gawati.org
Content-Length: 54

{"data":{"docTypes":"all","itemsFrom":1,"pageSize":5}}

-----

leads to response:

HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Access-Control-Allow-Origin: http://localhost:3000
Vary: Origin
Access-Control-Allow-Credentials: true
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 994
Date: Wed, 09 May 2018 08:34:36 GMT
Connection: close

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot read property &#39;akomaNtoso&#39; of undefined<br> &nbsp; &nbsp;at getOnlineDocumentFromAknObject (/home/gawatidevclientsrv/portal/docum
entmanage.js:277:53)<br> &nbsp; &nbsp;at packages.map (/home/gawatidevclientsrv/portal/documentmanage.js:318:24)<br> &nbsp; &nbsp;at Array.map (&lt;anonymous&gt
;)<br> &nbsp; &nbsp;at convertAknXmlToObjects (/home/gawatidevclientsrv/portal/documentmanage.js:317:31)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/
home/gawatidevclientsrv/portal/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/gawatidevclientsrv/portal/node_modules/express/lib
/router/route.js:137:13)<br> &nbsp; &nbsp;at axios.then (/home/gawatidevclientsrv/portal/documentmanage.js:342:13)<br> &nbsp; &nbsp;at &lt;anonymous&gt;<br> &nb
sp; &nbsp;at process._tickCallback (internal/process/next_tick.js:188:7)</pre>
</body>
</html>

which is an error condition, but should actually just be a valid empty result list / state 200

**Comment by ccsmart** [comment]
fix verified
